export const CREATE_MILESTONE_ROADMAP_REQUEST =
  "CREATE_MILESTONE_ROADMAP_REQUEST";
export const CREATE_MILESTONE_ROADMAP_SUCCESS =
  "CREATE_MILESTONE_ROADMAP_SUCCESS";
export const CREATE_MILESTONE_ROADMAP_FAILURE =
  "CREATE_MILESTONE_ROADMAP_FAILURE";

export const GET_MILESTONES_ROADMAPS_REQUEST =
  "GET_MILESTONES_ROADMAPS_REQUEST";
export const GET_MILESTONES_ROADMAPS_SUCCESS =
  "GET_MILESTONES_ROADMAPS_SUCCESS";
export const GET_MILESTONES_ROADMAPS_FAILURE =
  "GET_MILESTONES_ROADMAPS_FAILURE";

export const GET_MILESTONE_ROADMAP_REQUEST = "GET_MILESTONE_ROADMAP_REQUEST";
export const GET_MILESTONE_ROADMAP_SUCCESS = "GET_MILESTONE_ROADMAP_SUCCESS";
export const GET_MILESTONE_ROADMAP_FAILURE = "GET_MILESTONE_ROADMAP_FAILURE";

export const UPDATE_MILESTONE_ROADMAP_REQUEST =
  "UPDATE_MILESTONE_ROADMAP_REQUEST";
export const UPDATE_MILESTONE_ROADMAP_SUCCESS =
  "UPDATE_MILESTONE_ROADMAP_SUCCESS";
export const UPDATE_MILESTONE_ROADMAP_FAILURE =
  "UPDATE_MILESTONE_ROADMAP_FAILURE";

export const DELETE_MILESTONE_ROADMAP_REQUEST =
  "DELETE_MILESTONE_ROADMAP_REQUEST";
export const DELETE_MILESTONE_ROADMAP_SUCCESS =
  "DELETE_MILESTONE_ROADMAP_SUCCESS";
export const DELETE_MILESTONE_ROADMAP_FAILURE =
  "DELETE_MILESTONE_ROADMAP_FAILURE";

export const CLEAR_MILESTONE_ROADMAP_DETAILS =
  "CLEAR_MILESTONE_ROADMAP_DETAILS";
