export const CREATE_ASSET_CATEGORY_REQUEST = "CREATE_ASSET_CATEGORY_REQUEST";
export const CREATE_ASSET_CATEGORY_SUCCESS = "CREATE_ASSET_CATEGORY_SUCCESS";
export const CREATE_ASSET_CATEGORY_FAILURE = "CREATE_ASSET_CATEGORY_FAILURE";

export const GET_ASSET_CATEGORIES_REQUEST = "GET_ASSET_CATEGORIES_REQUEST";
export const GET_ASSET_CATEGORIES_SUCCESS = "GET_ASSET_CATEGORIES_SUCCESS";
export const GET_ASSET_CATEGORIES_FAILURE = "GET_ASSET_CATEGORIES_FAILURE";

export const GET_ASSET_CATEGORY_REQUEST = "GET_ASSET_CATEGORY_REQUEST";
export const GET_ASSET_CATEGORY_SUCCESS = "GET_ASSET_CATEGORY_SUCCESS";
export const GET_ASSET_CATEGORY_FAILURE = "GET_ASSET_CATEGORY_FAILURE";

export const UPDATE_ASSET_CATEGORY_REQUEST = "UPDATE_ASSET_CATEGORY_REQUEST";
export const UPDATE_ASSET_CATEGORY_SUCCESS = "UPDATE_ASSET_CATEGORY_SUCCESS";
export const UPDATE_ASSET_CATEGORY_FAILURE = "UPDATE_ASSET_CATEGORY_FAILURE";

export const DELETE_ASSET_CATEGORY_REQUEST = "DELETE_ASSET_CATEGORY_REQUEST";
export const DELETE_ASSET_CATEGORY_SUCCESS = "DELETE_ASSET_CATEGORY_SUCCESS";
export const DELETE_ASSET_CATEGORY_FAILURE = "DELETE_ASSET_CATEGORY_FAILURE";

export const CLEAR_ASSET_CATEGORY_DETAILS = "CLEAR_ASSET_CATEGORY_DETAILS";
