export const SEND_CHAT_QUERY = "SEND_CHAT_QUERY";
export const SEND_CHAT_QUERY_SUCCESS = "SEND_CHAT_QUERY_SUCCESS";
export const SEND_CHAT_QUERY_FAILURE = "SEND_CHAT_QUERY_FAILURE";
export const CHAT_CHUNK_RECEIVED = "CHAT_CHUNK_RECEIVED";
export const CLEAR_CHAT_HISTORY = "CLEAR_CHAT_HISTORY";

// History Management
export const FETCH_SESSIONS = "FETCH_SESSIONS";
export const FETCH_SESSIONS_SUCCESS = "FETCH_SESSIONS_SUCCESS";
export const FETCH_SESSIONS_FAILURE = "FETCH_SESSIONS_FAILURE";

export const FETCH_SESSION_MESSAGES = "FETCH_SESSION_MESSAGES";
export const FETCH_SESSION_MESSAGES_SUCCESS = "FETCH_SESSION_MESSAGES_SUCCESS";
export const FETCH_SESSION_MESSAGES_FAILURE = "FETCH_SESSION_MESSAGES_FAILURE";

export const DELETE_SESSION = "DELETE_SESSION";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS";
export const DELETE_SESSION_FAILURE = "DELETE_SESSION_FAILURE";

export const RENAME_SESSION = "RENAME_SESSION";
export const RENAME_SESSION_SUCCESS = "RENAME_SESSION_SUCCESS";
export const RENAME_SESSION_FAILURE = "RENAME_SESSION_FAILURE";

export const SET_ACTIVE_SESSION = "SET_ACTIVE_SESSION";
export const START_NEW_CHAT = "START_NEW_CHAT";
