export const SEND_CHAT_QUERY = "SEND_CHAT_QUERY";
export const SEND_CHAT_QUERY_SUCCESS = "SEND_CHAT_QUERY_SUCCESS";
export const SEND_CHAT_QUERY_FAILURE = "SEND_CHAT_QUERY_FAILURE";
export const CHAT_CHUNK_RECEIVED = "CHAT_CHUNK_RECEIVED";
export const CLEAR_CHAT_HISTORY = "CLEAR_CHAT_HISTORY";
