export const SEND_CHAT_QUERY = "SEND_CHAT_QUERY";
export const SEND_CHAT_QUERY_SUCCESS = "SEND_CHAT_QUERY_SUCCESS";
export const SEND_CHAT_QUERY_FAILURE = "SEND_CHAT_QUERY_FAILURE";
export const CHAT_CHUNK_RECEIVED = "CHAT_CHUNK_RECEIVED";
export const CLEAR_CHAT_HISTORY = "CLEAR_CHAT_HISTORY";

// Session History Actions
export const FETCH_CHAT_SESSIONS = "FETCH_CHAT_SESSIONS";
export const FETCH_CHAT_SESSIONS_SUCCESS = "FETCH_CHAT_SESSIONS_SUCCESS";
export const FETCH_CHAT_SESSIONS_FAILURE = "FETCH_CHAT_SESSIONS_FAILURE";

export const FETCH_SESSION_MESSAGES = "FETCH_SESSION_MESSAGES";
export const FETCH_SESSION_MESSAGES_SUCCESS = "FETCH_SESSION_MESSAGES_SUCCESS";
export const FETCH_SESSION_MESSAGES_FAILURE = "FETCH_SESSION_MESSAGES_FAILURE";

export const SET_CURRENT_SESSION_ID = "SET_CURRENT_SESSION_ID";
export const UPDATE_SESSION_ID = "UPDATE_SESSION_ID";

export const DELETE_CHAT_SESSION = "DELETE_CHAT_SESSION";
export const DELETE_CHAT_SESSION_SUCCESS = "DELETE_CHAT_SESSION_SUCCESS";
export const DELETE_CHAT_SESSION_FAILURE = "DELETE_CHAT_SESSION_FAILURE";

export const RENAME_CHAT_SESSION = "RENAME_CHAT_SESSION";
export const RENAME_CHAT_SESSION_SUCCESS = "RENAME_CHAT_SESSION_SUCCESS";
export const RENAME_CHAT_SESSION_FAILURE = "RENAME_CHAT_SESSION_FAILURE";
