export const CREATE_LEAVE_TYPE_REQUEST = "CREATE_LEAVE_TYPE_REQUEST";
export const CREATE_LEAVE_TYPE_SUCCESS = "CREATE_LEAVE_TYPE_SUCCESS";
export const CREATE_LEAVE_TYPE_FAILURE = "CREATE_LEAVE_TYPE_FAILURE";

export const GET_LEAVE_TYPES_REQUEST = "GET_LEAVE_TYPES_REQUEST";
export const GET_LEAVE_TYPES_SUCCESS = "GET_LEAVE_TYPES_SUCCESS";
export const GET_LEAVE_TYPES_FAILURE = "GET_LEAVE_TYPES_FAILURE";

export const GET_LEAVE_TYPE_REQUEST = "GET_LEAVE_TYPE_REQUEST";
export const GET_LEAVE_TYPE_SUCCESS = "GET_LEAVE_TYPE_SUCCESS";
export const GET_LEAVE_TYPE_FAILURE = "GET_LEAVE_TYPE_FAILURE";

export const UPDATE_LEAVE_TYPE_REQUEST = "UPDATE_LEAVE_TYPE_REQUEST";
export const UPDATE_LEAVE_TYPE_SUCCESS = "UPDATE_LEAVE_TYPE_SUCCESS";
export const UPDATE_LEAVE_TYPE_FAILURE = "UPDATE_LEAVE_TYPE_FAILURE";

export const DELETE_LEAVE_TYPE_REQUEST = "DELETE_LEAVE_TYPE_REQUEST";
export const DELETE_LEAVE_TYPE_SUCCESS = "DELETE_LEAVE_TYPE_SUCCESS";
export const DELETE_LEAVE_TYPE_FAILURE = "DELETE_LEAVE_TYPE_FAILURE";

export const CLEAR_LEAVE_TYPE_DETAILS = "CLEAR_LEAVE_TYPE_DETAILS";
