export const CREATE_LEAVE_REQUEST_REQUEST = "CREATE_LEAVE_REQUEST_REQUEST";
export const CREATE_LEAVE_REQUEST_SUCCESS = "CREATE_LEAVE_REQUEST_SUCCESS";
export const CREATE_LEAVE_REQUEST_FAILURE = "CREATE_LEAVE_REQUEST_FAILURE";

export const GET_LEAVE_REQUESTS_REQUEST = "GET_LEAVE_REQUESTS_REQUEST";
export const GET_LEAVE_REQUESTS_SUCCESS = "GET_LEAVE_REQUESTS_SUCCESS";
export const GET_LEAVE_REQUESTS_FAILURE = "GET_LEAVE_REQUESTS_FAILURE";

export const GET_LEAVE_REQUEST_REQUEST = "GET_LEAVE_REQUEST_REQUEST";
export const GET_LEAVE_REQUEST_SUCCESS = "GET_LEAVE_REQUEST_SUCCESS";
export const GET_LEAVE_REQUEST_FAILURE = "GET_LEAVE_REQUEST_FAILURE";

export const UPDATE_LEAVE_REQUEST_REQUEST = "UPDATE_LEAVE_REQUEST_REQUEST";
export const UPDATE_LEAVE_REQUEST_SUCCESS = "UPDATE_LEAVE_REQUEST_SUCCESS";
export const UPDATE_LEAVE_REQUEST_FAILURE = "UPDATE_LEAVE_REQUEST_FAILURE";

export const UPDATE_LEAVE_STATUS_REQUEST = "UPDATE_LEAVE_STATUS_REQUEST";
export const UPDATE_LEAVE_STATUS_SUCCESS = "UPDATE_LEAVE_STATUS_SUCCESS";
export const UPDATE_LEAVE_STATUS_FAILURE = "UPDATE_LEAVE_STATUS_FAILURE";

export const DELETE_LEAVE_REQUEST_REQUEST = "DELETE_LEAVE_REQUEST_REQUEST";
export const DELETE_LEAVE_REQUEST_SUCCESS = "DELETE_LEAVE_REQUEST_SUCCESS";
export const DELETE_LEAVE_REQUEST_FAILURE = "DELETE_LEAVE_REQUEST_FAILURE";

export const CLEAR_LEAVE_REQUEST_DETAILS = "CLEAR_LEAVE_REQUEST_DETAILS";
