export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export const GET_TASK_REQUEST = "GET_TASK_REQUEST";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAILURE = "GET_TASK_FAILURE";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const SUBMIT_EOD_REPORT_REQUEST = "SUBMIT_EOD_REPORT_REQUEST";
export const SUBMIT_EOD_REPORT_SUCCESS = "SUBMIT_EOD_REPORT_SUCCESS";
export const SUBMIT_EOD_REPORT_FAILURE = "SUBMIT_EOD_REPORT_FAILURE";

export const GET_EOD_REPORTS_REQUEST = "GET_EOD_REPORTS_REQUEST";
export const GET_EOD_REPORTS_SUCCESS = "GET_EOD_REPORTS_SUCCESS";
export const GET_EOD_REPORTS_FAILURE = "GET_EOD_REPORTS_FAILURE";
