export const CREATE_DOCUMENT_CATEGORY_REQUEST = "CREATE_DOCUMENT_CATEGORY_REQUEST";
export const CREATE_DOCUMENT_CATEGORY_SUCCESS = "CREATE_DOCUMENT_CATEGORY_SUCCESS";
export const CREATE_DOCUMENT_CATEGORY_FAILURE = "CREATE_DOCUMENT_CATEGORY_FAILURE";

export const GET_DOCUMENT_CATEGORIES_REQUEST = "GET_DOCUMENT_CATEGORIES_REQUEST";
export const GET_DOCUMENT_CATEGORIES_SUCCESS = "GET_DOCUMENT_CATEGORIES_SUCCESS";
export const GET_DOCUMENT_CATEGORIES_FAILURE = "GET_DOCUMENT_CATEGORIES_FAILURE";

export const GET_DOCUMENT_CATEGORY_REQUEST = "GET_DOCUMENT_CATEGORY_REQUEST";
export const GET_DOCUMENT_CATEGORY_SUCCESS = "GET_DOCUMENT_CATEGORY_SUCCESS";
export const GET_DOCUMENT_CATEGORY_FAILURE = "GET_DOCUMENT_CATEGORY_FAILURE";

export const UPDATE_DOCUMENT_CATEGORY_REQUEST = "UPDATE_DOCUMENT_CATEGORY_REQUEST";
export const UPDATE_DOCUMENT_CATEGORY_SUCCESS = "UPDATE_DOCUMENT_CATEGORY_SUCCESS";
export const UPDATE_DOCUMENT_CATEGORY_FAILURE = "UPDATE_DOCUMENT_CATEGORY_FAILURE";

export const DELETE_DOCUMENT_CATEGORY_REQUEST = "DELETE_DOCUMENT_CATEGORY_REQUEST";
export const DELETE_DOCUMENT_CATEGORY_SUCCESS = "DELETE_DOCUMENT_CATEGORY_SUCCESS";
export const DELETE_DOCUMENT_CATEGORY_FAILURE = "DELETE_DOCUMENT_CATEGORY_FAILURE";

export const CLEAR_DOCUMENT_CATEGORY_DETAILS = "CLEAR_DOCUMENT_CATEGORY_DETAILS";
