export const GENERATE_PAYSLIP_REQUEST = "GENERATE_PAYSLIP_REQUEST";
export const GENERATE_PAYSLIP_SUCCESS = "GENERATE_PAYSLIP_SUCCESS";
export const GENERATE_PAYSLIP_FAILURE = "GENERATE_PAYSLIP_FAILURE";

export const GET_PAYSLIPS_REQUEST = "GET_PAYSLIPS_REQUEST";
export const GET_PAYSLIPS_SUCCESS = "GET_PAYSLIPS_SUCCESS";
export const GET_PAYSLIPS_FAILURE = "GET_PAYSLIPS_FAILURE";

export const GET_LATEST_PAYSLIP_REQUEST = "GET_LATEST_PAYSLIP_REQUEST";
export const GET_LATEST_PAYSLIP_SUCCESS = "GET_LATEST_PAYSLIP_SUCCESS";
export const GET_LATEST_PAYSLIP_FAILURE = "GET_LATEST_PAYSLIP_FAILURE";

export const DOWNLOAD_PAYSLIP_REQUEST = "DOWNLOAD_PAYSLIP_REQUEST";
export const DOWNLOAD_PAYSLIP_SUCCESS = "DOWNLOAD_PAYSLIP_SUCCESS";
export const DOWNLOAD_PAYSLIP_FAILURE = "DOWNLOAD_PAYSLIP_FAILURE";

export const UPDATE_PAYSLIP_REQUEST = "UPDATE_PAYSLIP_REQUEST";
export const UPDATE_PAYSLIP_SUCCESS = "UPDATE_PAYSLIP_SUCCESS";
export const UPDATE_PAYSLIP_FAILURE = "UPDATE_PAYSLIP_FAILURE";

export const CREATE_PAYSLIP_STATES = "CREATE_PAYSLIP_STATES";
