export const CREATE_EXPENSE_CATEGORY_REQUEST = "CREATE_EXPENSE_CATEGORY_REQUEST";
export const CREATE_EXPENSE_CATEGORY_SUCCESS = "CREATE_EXPENSE_CATEGORY_SUCCESS";
export const CREATE_EXPENSE_CATEGORY_FAILURE = "CREATE_EXPENSE_CATEGORY_FAILURE";

export const GET_EXPENSE_CATEGORIES_REQUEST = "GET_EXPENSE_CATEGORIES_REQUEST";
export const GET_EXPENSE_CATEGORIES_SUCCESS = "GET_EXPENSE_CATEGORIES_SUCCESS";
export const GET_EXPENSE_CATEGORIES_FAILURE = "GET_EXPENSE_CATEGORIES_FAILURE";

export const GET_EXPENSE_CATEGORY_REQUEST = "GET_EXPENSE_CATEGORY_REQUEST";
export const GET_EXPENSE_CATEGORY_SUCCESS = "GET_EXPENSE_CATEGORY_SUCCESS";
export const GET_EXPENSE_CATEGORY_FAILURE = "GET_EXPENSE_CATEGORY_FAILURE";

export const UPDATE_EXPENSE_CATEGORY_REQUEST = "UPDATE_EXPENSE_CATEGORY_REQUEST";
export const UPDATE_EXPENSE_CATEGORY_SUCCESS = "UPDATE_EXPENSE_CATEGORY_SUCCESS";
export const UPDATE_EXPENSE_CATEGORY_FAILURE = "UPDATE_EXPENSE_CATEGORY_FAILURE";

export const DELETE_EXPENSE_CATEGORY_REQUEST = "DELETE_EXPENSE_CATEGORY_REQUEST";
export const DELETE_EXPENSE_CATEGORY_SUCCESS = "DELETE_EXPENSE_CATEGORY_SUCCESS";
export const DELETE_EXPENSE_CATEGORY_FAILURE = "DELETE_EXPENSE_CATEGORY_FAILURE";

export const CLEAR_EXPENSE_CATEGORY_DETAILS = "CLEAR_EXPENSE_CATEGORY_DETAILS";
