export const CREATE_ASSET_REQUEST = "CREATE_ASSET_REQUEST";
export const CREATE_ASSET_SUCCESS = "CREATE_ASSET_SUCCESS";
export const CREATE_ASSET_FAILURE = "CREATE_ASSET_FAILURE";

export const GET_ASSETS_REQUEST = "GET_ASSETS_REQUEST";
export const GET_ASSETS_SUCCESS = "GET_ASSETS_SUCCESS";
export const GET_ASSETS_FAILURE = "GET_ASSETS_FAILURE";

export const GET_ASSET_REQUEST = "GET_ASSET_REQUEST";
export const GET_ASSET_SUCCESS = "GET_ASSET_SUCCESS";
export const GET_ASSET_FAILURE = "GET_ASSET_FAILURE";

export const UPDATE_ASSET_REQUEST = "UPDATE_ASSET_REQUEST";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const UPDATE_ASSET_FAILURE = "UPDATE_ASSET_FAILURE";

export const DELETE_ASSET_REQUEST = "DELETE_ASSET_REQUEST";
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS";
export const DELETE_ASSET_FAILURE = "DELETE_ASSET_FAILURE";

export const ASSIGN_ASSET_REQUEST = "ASSIGN_ASSET_REQUEST";
export const ASSIGN_ASSET_SUCCESS = "ASSIGN_ASSET_SUCCESS";
export const ASSIGN_ASSET_FAILURE = "ASSIGN_ASSET_FAILURE";

export const GET_ASSETS_BY_EMPLOYEE_REQUEST = "GET_ASSETS_BY_EMPLOYEE_REQUEST";
export const GET_ASSETS_BY_EMPLOYEE_SUCCESS = "GET_ASSETS_BY_EMPLOYEE_SUCCESS";
export const GET_ASSETS_BY_EMPLOYEE_FAILURE = "GET_ASSETS_BY_EMPLOYEE_FAILURE";

export const CLEAR_ASSET_DETAILS = "CLEAR_ASSET_DETAILS";
