// Create
export const CREATE_PAYSLIP_COMPONENT_REQUEST =
  "CREATE_PAYSLIP_COMPONENT_REQUEST";
export const CREATE_PAYSLIP_COMPONENT_SUCCESS =
  "CREATE_PAYSLIP_COMPONENT_SUCCESS";
export const CREATE_PAYSLIP_COMPONENT_FAILURE =
  "CREATE_PAYSLIP_COMPONENT_FAILURE";

// Get All
export const GET_PAYSLIP_COMPONENTS_REQUEST = "GET_PAYSLIP_COMPONENTS_REQUEST";
export const GET_PAYSLIP_COMPONENTS_SUCCESS = "GET_PAYSLIP_COMPONENTS_SUCCESS";
export const GET_PAYSLIP_COMPONENTS_FAILURE = "GET_PAYSLIP_COMPONENTS_FAILURE";

// Update
export const UPDATE_PAYSLIP_COMPONENT_REQUEST =
  "UPDATE_PAYSLIP_COMPONENT_REQUEST";
export const UPDATE_PAYSLIP_COMPONENT_SUCCESS =
  "UPDATE_PAYSLIP_COMPONENT_SUCCESS";
export const UPDATE_PAYSLIP_COMPONENT_FAILURE =
  "UPDATE_PAYSLIP_COMPONENT_FAILURE";

// Delete
export const DELETE_PAYSLIP_COMPONENT_REQUEST =
  "DELETE_PAYSLIP_COMPONENT_REQUEST";
export const DELETE_PAYSLIP_COMPONENT_SUCCESS =
  "DELETE_PAYSLIP_COMPONENT_SUCCESS";
export const DELETE_PAYSLIP_COMPONENT_FAILURE =
  "DELETE_PAYSLIP_COMPONENT_FAILURE";

// Reset States
export const CLEAR_PAYSLIP_COMPONENT_STATES = "CLEAR_PAYSLIP_COMPONENT_STATES";
