export const CREATE_NDA_REQUEST = "CREATE_NDA_REQUEST";
export const CREATE_NDA_SUCCESS = "CREATE_NDA_SUCCESS";
export const CREATE_NDA_FAILURE = "CREATE_NDA_FAILURE";

export const GET_NDA_REQUEST = "GET_NDA_REQUEST";
export const GET_NDA_SUCCESS = "GET_NDA_SUCCESS";
export const GET_NDA_FAILURE = "GET_NDA_FAILURE";

export const SIGN_NDA_REQUEST = "SIGN_NDA_REQUEST";
export const SIGN_NDA_SUCCESS = "SIGN_NDA_SUCCESS";
export const SIGN_NDA_FAILURE = "SIGN_NDA_FAILURE";

export const CLEAR_NDA = "CLEAR_NDA";
