export const GENERATE_NDA_REQUEST = "GENERATE_NDA_REQUEST";
export const GENERATE_NDA_SUCCESS = "GENERATE_NDA_SUCCESS";
export const GENERATE_NDA_FAILURE = "GENERATE_NDA_FAILURE";

export const GET_NDA_LIST_REQUEST = "GET_NDA_LIST_REQUEST";
export const GET_NDA_LIST_SUCCESS = "GET_NDA_LIST_SUCCESS";
export const GET_NDA_LIST_FAILURE = "GET_NDA_LIST_FAILURE";

export const GET_NDA_BY_TOKEN_REQUEST = "GET_NDA_BY_TOKEN_REQUEST";
export const GET_NDA_BY_TOKEN_SUCCESS = "GET_NDA_BY_TOKEN_SUCCESS";
export const GET_NDA_BY_TOKEN_FAILURE = "GET_NDA_BY_TOKEN_FAILURE";

export const UPLOAD_NDA_DOCUMENTS_REQUEST = "UPLOAD_NDA_DOCUMENTS_REQUEST";
export const UPLOAD_NDA_DOCUMENTS_SUCCESS = "UPLOAD_NDA_DOCUMENTS_SUCCESS";
export const UPLOAD_NDA_DOCUMENTS_FAILURE = "UPLOAD_NDA_DOCUMENTS_FAILURE";

export const SIGN_NDA_REQUEST = "SIGN_NDA_REQUEST";
export const SIGN_NDA_SUCCESS = "SIGN_NDA_SUCCESS";
export const SIGN_NDA_FAILURE = "SIGN_NDA_FAILURE";

export const CLEAR_NDA_STATE = "CLEAR_NDA_STATE";
