export const CLOCK_IN_REQUEST = "CLOCK_IN_REQUEST";
export const CLOCK_IN_SUCCESS = "CLOCK_IN_SUCCESS";
export const CLOCK_IN_FAILURE = "CLOCK_IN_FAILURE";

export const CLOCK_OUT_REQUEST = "CLOCK_OUT_REQUEST";
export const CLOCK_OUT_SUCCESS = "CLOCK_OUT_SUCCESS";
export const CLOCK_OUT_FAILURE = "CLOCK_OUT_FAILURE";

export const GET_MY_ATTENDANCE_HISTORY_REQUEST = "GET_MY_ATTENDANCE_HISTORY_REQUEST";
export const GET_MY_ATTENDANCE_HISTORY_SUCCESS = "GET_MY_ATTENDANCE_HISTORY_SUCCESS";
export const GET_MY_ATTENDANCE_HISTORY_FAILURE = "GET_MY_ATTENDANCE_HISTORY_FAILURE";

export const GET_ALL_ATTENDANCE_REQUEST = "GET_ALL_ATTENDANCE_REQUEST";
export const GET_ALL_ATTENDANCE_SUCCESS = "GET_ALL_ATTENDANCE_SUCCESS";
export const GET_ALL_ATTENDANCE_FAILURE = "GET_ALL_ATTENDANCE_FAILURE";

export const IMPORT_ATTENDANCE_REQUEST = "IMPORT_ATTENDANCE_REQUEST";
export const IMPORT_ATTENDANCE_SUCCESS = "IMPORT_ATTENDANCE_SUCCESS";
export const IMPORT_ATTENDANCE_FAILURE = "IMPORT_ATTENDANCE_FAILURE";

export const CLEAR_ATTENDANCE_STATUS = "CLEAR_ATTENDANCE_STATUS";
